// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sc_mapping
NumericVector sc_mapping(NumericVector x1, NumericVector y1, NumericVector x2, int n1, int n2);
RcppExport SEXP _SurvBD_sc_mapping(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP n1SEXP, SEXP n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    rcpp_result_gen = Rcpp::wrap(sc_mapping(x1, y1, x2, n1, n2));
    return rcpp_result_gen;
END_RCPP
}
// sc_mapping_one
double sc_mapping_one(NumericVector x1, NumericVector y1, double x2, int n1);
RcppExport SEXP _SurvBD_sc_mapping_one(SEXP x1SEXP, SEXP y1SEXP, SEXP x2SEXP, SEXP n1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< double >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    rcpp_result_gen = Rcpp::wrap(sc_mapping_one(x1, y1, x2, n1));
    return rcpp_result_gen;
END_RCPP
}
// SurvBD_IPW
double SurvBD_IPW(NumericVector time1, NumericVector time2, NumericVector delta1, NumericVector delta2, NumericVector sc1, NumericVector sc2, NumericVector sc1AtSamp2, NumericVector sc2AtSamp1, int n1, int n2);
RcppExport SEXP _SurvBD_SurvBD_IPW(SEXP time1SEXP, SEXP time2SEXP, SEXP delta1SEXP, SEXP delta2SEXP, SEXP sc1SEXP, SEXP sc2SEXP, SEXP sc1AtSamp2SEXP, SEXP sc2AtSamp1SEXP, SEXP n1SEXP, SEXP n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time1(time1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time2(time2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc1(sc1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc2(sc2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc1AtSamp2(sc1AtSamp2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc2AtSamp1(sc2AtSamp1SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    rcpp_result_gen = Rcpp::wrap(SurvBD_IPW(time1, time2, delta1, delta2, sc1, sc2, sc1AtSamp2, sc2AtSamp1, n1, n2));
    return rcpp_result_gen;
END_RCPP
}
// SurvBD_IPW_accelerated
double SurvBD_IPW_accelerated(NumericVector time1, NumericVector time2, NumericVector delta1, NumericVector delta2, NumericVector sc1, NumericVector sc2, NumericVector rank_X, NumericVector rank_Y, NumericVector rank_XY, NumericVector rank_XX, NumericVector rank_YY, NumericVector rank_1_1, NumericVector rank_1_2, NumericVector rank_2_1, NumericVector rank_2_2, int n1, int n2);
RcppExport SEXP _SurvBD_SurvBD_IPW_accelerated(SEXP time1SEXP, SEXP time2SEXP, SEXP delta1SEXP, SEXP delta2SEXP, SEXP sc1SEXP, SEXP sc2SEXP, SEXP rank_XSEXP, SEXP rank_YSEXP, SEXP rank_XYSEXP, SEXP rank_XXSEXP, SEXP rank_YYSEXP, SEXP rank_1_1SEXP, SEXP rank_1_2SEXP, SEXP rank_2_1SEXP, SEXP rank_2_2SEXP, SEXP n1SEXP, SEXP n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time1(time1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time2(time2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc1(sc1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sc2(sc2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_X(rank_XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_Y(rank_YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_XY(rank_XYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_XX(rank_XXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_YY(rank_YYSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_1_1(rank_1_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_1_2(rank_1_2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_2_1(rank_2_1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rank_2_2(rank_2_2SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    rcpp_result_gen = Rcpp::wrap(SurvBD_IPW_accelerated(time1, time2, delta1, delta2, sc1, sc2, rank_X, rank_Y, rank_XY, rank_XX, rank_YY, rank_1_1, rank_1_2, rank_2_1, rank_2_2, n1, n2));
    return rcpp_result_gen;
END_RCPP
}
// SurvBD_KMW
double SurvBD_KMW(NumericVector time1, NumericVector time2, NumericVector delta1, NumericVector delta2, NumericVector weight1, NumericVector weight2, int n1, int n2);
RcppExport SEXP _SurvBD_SurvBD_KMW(SEXP time1SEXP, SEXP time2SEXP, SEXP delta1SEXP, SEXP delta2SEXP, SEXP weight1SEXP, SEXP weight2SEXP, SEXP n1SEXP, SEXP n2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time1(time1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time2(time2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta1(delta1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type delta2(delta2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight1(weight1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weight2(weight2SEXP);
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    rcpp_result_gen = Rcpp::wrap(SurvBD_KMW(time1, time2, delta1, delta2, weight1, weight2, n1, n2));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SurvBD_sc_mapping", (DL_FUNC) &_SurvBD_sc_mapping, 5},
    {"_SurvBD_sc_mapping_one", (DL_FUNC) &_SurvBD_sc_mapping_one, 4},
    {"_SurvBD_SurvBD_IPW", (DL_FUNC) &_SurvBD_SurvBD_IPW, 10},
    {"_SurvBD_SurvBD_IPW_accelerated", (DL_FUNC) &_SurvBD_SurvBD_IPW_accelerated, 17},
    {"_SurvBD_SurvBD_KMW", (DL_FUNC) &_SurvBD_SurvBD_KMW, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SurvBD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
