# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sc_mapping <- function(x1, y1, x2, n1, n2) {
    .Call('_SurvBD_sc_mapping', PACKAGE = 'SurvBD', x1, y1, x2, n1, n2)
}

sc_mapping_one <- function(x1, y1, x2, n1) {
    .Call('_SurvBD_sc_mapping_one', PACKAGE = 'SurvBD', x1, y1, x2, n1)
}

SurvBD_IPW <- function(time1, time2, delta1, delta2, sc1, sc2, sc1AtSamp2, sc2AtSamp1, n1, n2) {
    .Call('_SurvBD_SurvBD_IPW', PACKAGE = 'SurvBD', time1, time2, delta1, delta2, sc1, sc2, sc1AtSamp2, sc2AtSamp1, n1, n2)
}

SurvBD_IPW_accelerated <- function(time1, time2, delta1, delta2, sc1, sc2, rank_X, rank_Y, rank_XY, rank_XX, rank_YY, rank_1_1, rank_1_2, rank_2_1, rank_2_2, n1, n2) {
    .Call('_SurvBD_SurvBD_IPW_accelerated', PACKAGE = 'SurvBD', time1, time2, delta1, delta2, sc1, sc2, rank_X, rank_Y, rank_XY, rank_XX, rank_YY, rank_1_1, rank_1_2, rank_2_1, rank_2_2, n1, n2)
}

SurvBD_KMW <- function(time1, time2, delta1, delta2, weight1, weight2, n1, n2) {
    .Call('_SurvBD_SurvBD_KMW', PACKAGE = 'SurvBD', time1, time2, delta1, delta2, weight1, weight2, n1, n2)
}

